server:
  port: 8888
idServiceUrl: ${ID_SERVICE_URL:http://localhost:8080/uaa}
spring: 
  thymeleaf:
    cache: false
  oauth2:
    client:
      authorizationUri: ${idServiceUrl}/oauth/authorize
      accessTokenUri: ${idServiceUrl}/oauth/token
      clientId: oauth_showcase_password_grant
      clientSecret: secret
logging.level:
  org.springframework.security: DEBUG
