security:
  ignored: /favicon.ico
  basic:
    enabled: false
uaa:
  location: ${UAA_LOCATION:http://localhost:8080/uaa}
spring: 
  oauth2:
    client:
      accessTokenUri: ${uaa.location}/oauth/token
      userAuthorizationUri: ${uaa.location}/oauth/authorize
      clientId: oauth_showcase_authorization_code
      clientSecret: secret
    resource:
      tokenInfoUri: ${uaa.location}/check_token
      id: openid
    
