security:
  ignored: /favicon.ico, /
  basic:
    enabled: false
idServiceUrl: ${ID_SERVICE_URL:http://localhost:8080/uaa}
spring: 
  oauth2:
    client:
      accessTokenUri: ${idServiceUrl}/oauth/token
      userAuthorizationUri: ${idServiceUrl}/oauth/authorize
      clientId: oauth_showcase_authorization_code
      clientSecret: secret
    resource:
      jwt:
        keyUri: ${idServiceUrl}/token_key
      id: openid
      serviceId: ${PREFIX:}resource
