security:
  ignored: /favicon.ico, /
  basic:
    enabled: false
idServiceUrl: ${ID_SERVICE_URL}
spring.oauth2:
    client:
      authorizationUri: ${ID_SERVICE_URL}/oauth/authorize
      accessTokenUri: ${ID_SERVICE_URL}/oauth/token
      clientId: ${CLIENT_ID}
      clientSecret: ${CLIENT_SECRET}
