server:
  port: 8888
idServiceUrl: ${ID_SERVICE_URL:https://localhost:8080/uaa}
spring: 
  thymeleaf:
    cache: false
  oauth2:
    client:
      clientId: oauth_showcase_implicit_grant
      accessTokenUri: ${idServiceUrl}/oauth/token
      userAuthorizationUri: ${idServiceUrl}/oauth/authorize
    resource:
      jwt.keyUri: ${idServiceUrl}/token_key
      
logging.level:
  org.springframework.security: DEBUG